# BAB 2 Kajian Pustaka {.unnumbered}

## Kajian Teori {.unnumbered}

### ***1. Programme for International Student Assessment*** **(PISA)** {.unnumbered}

PISA merupakan program yang didirikan oleh *Organization for Economic Co-Operation and Development* (OECD) pada tahun 1997 dengan tujuan untuk menilai kemampuan siswa yang berusia 15 tahun dalam bidang membaca, matematika, sains, dan mengukur keterampilan mereka dalam menerapkan apa yang telah mereka pelajari di sekolah dalam kehidupan sehari-hari. PISA sudah terlaksana sebanyak delapan kali dengan putaran pertama dilaksanakan pada tahun 2000 dan putaran kedelapan dilaksanakan pada tahun 2022. PISA merupakan program berkelanjutan yang dapat bermanfaat bagi pembuat kebijakan pendidikan dan penerapannya. Melalui hasil PISA, para pembuat kebijakan dapat mengukur keterampilan dan pengetahuan siswa serta membandingkannya dengan siswa di negara-negara lain. Mereka juga dapat menetapkan target kebijakan dengan sasaran terukur yang telah dicapai dalam sistem pendidikan negara  lain, serta dapat mempelajari  kebijakan-kebijakan dan praktik-praktik pendidikan di negara lain yang telah menunjukkan hasil prestasi belajar yang lebih baik. Indonesia telah mengikuti penilaian PISA sejak putaran pertama hingga putaran ketujuh. Dari keikutsertaannya tersebut, Indonesia berhasil untuk meningkatkan nilainya (PISA Governing Board Indonesia, 2019).

PISA 2018 fokus pada penilaian membaca, dengan matematika, sains dan kompetensi global sebagai bidang penilaian lain. Dalam PISA 2018 juga disertai penilaian literasi keuangan anak muda yang bersifat opsional untuk negara-negara ekonomi. Responden PISA 2018 berjumlah kurang lebih 600.000 siswa yang mewakili sekitar 32 juta anak berusia 15 tahun dari 79 negara yang mengikuti penilaian PISA. Penilaian PISA 2018 meliputi tes berbasis komputer dengan soal tes campuran dari pertanyaan pilihan ganda dan uraian, yang mengharuskan mereka untuk menyusun tanggapannya sendiri (OECD, 2019d).

Melalui program PISA, informasi mengenai latar belakang siswa, sikap siswa terhadap belajar, dan lingkungan belajar siswa dapat diperoleh. Informasi-informasi tersebut memberikan tipe tipe hasil utama penilaian PISA yaitu (PISA Governing Board Indonesia, 2019) :

1.  Indikator-indikator dasar sebagai profil batas bawah keterampilan dan pengetahuan siswa.

2.  Indikator-indikator yang terbentuk dari hasil kuesioner yang menunjukkan bagaimana keterampilan yang dimiliki siswa berkaitan dengan berbagai variabel demografi, sosial ekonomi, pendidikan, serta hasil dari pendidikan yang lebih luas seperti pencapaian tingkat pendidikan dan kesejahteraan.

3.  Indikator-indikator dalam tren, dimulai dengan keikutsertaan negara untuk ketujuh kalinya dalam tes PISA, yang menunjukkan perubahan dalam nilai tengah hasil PISA, dalam variasi hasil di antara siswa, dan dalam hubungan antara hasil dengan berbagai variabel khusus siswa, sekolah, dan sistem.

### **2. Literasi Membaca** {.unnumbered}

Di seluruh dunia, literasi membaca berhubungan langsung dengan alasan seseorang membaca, termasuk membaca karena hobi, ingin belajar dan berpartisipasi dalam masyarakat. Oleh karena itu, literasi membaca dapat didefinisikan sebagai kemampuan memahami dan menggunakan berbagai ragam teks serta  ragam bahasa tulisan formal di masyarakat;kemudian  kemampuan tersebut digunakan dalam belajar, berpartisipasi dalam komunitas membaca di sekolah, dalam kehidupan sehari-hari dan dalam hal yang berkaitan dengan hobi (Mullis & Martin, 2019).

Literasi membaca adalah kemampuan untuk memahami dan menggunakan bentuk-bentuk bahasa tertulis yang dibutuhkan oleh masyarakat dan atau dihargai oleh individu. Menurut OECD literasi membaca dapat didefinisikan sebagai kapasitas individu dalam memahami, menggunakan, merenungkan, dan tercurah secara penuh pada teks tertulis untuk mencapai cita-cita, mengembangkan pengetahuan dan potensi, serta berpartisipasi di dalam masyarakat (PISA Governing Board Indonesia, 2019). Dari berbagai definisi literasi membaca tersebut, maka dapat disimpulkan bahwa literasi membaca tidak sebatas membaca huruf, kata atau kalimat namun sejauh mana individu dapat mengaplikasikan hasil yang ia peroleh setelah membaca untuk menjalani kehidupan sehari-hari. Membaca merupakan kunci untuk mempelajari segala ilmu pengetahuan, termasuk informasi dan petunjuk sehari-hari yang berdampak besar bagi kehidupan.

### **3. Status Sosial Ekonomi  (SES)** {.unnumbered}

Menurut Prasetyaningsih (2019) status sosial ekonomi merupakan posisi seseorang dalam masyarakat yang berkaitan dengan hak-hak dan kewajibannya, serta peran yang dimiliki dalam masyarakat. Status sosial ekonomi siswa merupakan ukuran sumber daya keluarga, termasuk modal keuangan, modal sosial, modal budaya, dan modal manusia, serta posisi sosial keluarga atau rumah tangga siswa. Faktor-faktor yang menentukan status sosial ekonomi secara umum antara lain kekayaan dan penghasilan, pekerjaan, serta pendidikan (OECD, 2019a).

Latar belakang sosial ekonomi siswa tidak pernah lepas dari peranan orang tua mereka. Perbedaan status sosial ekonomi orang tua akan menyebabkan perbedaan pengalaman siswa. Latar belakang sosial ekonomi orang tua seperti jabatan dan pekerjaan akan mempengaruhi anaknya dalam berlaku dalam kehidupan sehari-hari, seperti menggunakan dan mengelola uang atau bagaimana mereka harus memiliki gaya hidup. Seorang siswa yang berasal dari orang tua dengan status sosial ekonomi cukup, diberi fasilitas lengkap dan uang saku yang lebih akan memiliki kesempatan untuk memenuhi kebutuhan sekolah lebih besar dibandingkan dengan siswa yang berasal dari keluarga dengan sosial ekonomi yang rendah.

Status sosial ekonomi berpengaruh terhadap prestasi belajar siswa. Hasil penelitian Whitney & Bergin (2018) menunjukkan bahwa terdapat kesenjangan dalam keterlibatan kelas, dimana siswa yang berasal dari keluarga berpenghasilan rendah memiliki keterlibatan kelas yang lebih rendah dibandingkan dengan siswa yang berasal dari keluarga dengan penghasilan tinggi. Hal tersebut tentu saja akan mempengaruhi prestasi belajarnya di sekolah. Penelitian yang dilakukan oleh Van Bergen dkk., (2017) menunjukkan bahwa tingkat pendidikan keluarga berkaitan dengan prestasi membaca siswa melalui keterampilan membaca orang tua mereka. Orang tua dengan pendidikan  yang tinggi memiliki modal untuk mengajarkan membaca kepada anak-anak mereka dan  memberikan contoh yang baik melalui pembiasaan membaca kepada anak-anak mereka. Pembiasaan membaca pada anak dapat meningkatkan pendidikan mereka karena secara substantif anak-anak akan memiliki keterampilan kognitif dan memiliki kosakata yang lebih banyak (Evans dkk., 2014).

Penelitian-penelitian sebelumnya juga telah menemukan bahwa status sosial ekonomi orang tua berkaitan dengan kesejahteraan anak, pola asuh yang baik, dan komunikasi antara orang tua dan anak yang berkualitas (Duncan dkk., 2011). Terdapat bukti bahwa perbedaan antara anak laki-laki dan perempuan lebih kecil pada keluarga dengan SES yang lebih tinggi (de Zeeuw dkk., 2019). Sehingga prestasi siswa laki-laki memiliki kaitan yang lebih erat dengan SES dibandingkan dengan prestasi akademik siswa perempuan. Menurut Hamplová & Raudenská (2021) keluarga dengan budaya ilmiah yang rendah memiliki aspirasi yang lebih tinggi untuk anak perempuan daripada anak laki-laki, sedangkan keluarga dengan budaya ilmiah yang tinggi  memiliki aspirasi yang sama untuk anak laki-laki dan perempuan. Oleh karena itu, pendidikan orang tua dan budaya ilmiah keluarga dapat mempengaruhi prestasi akademik siswa laki-laki dan perempuan.

### **4. Motivasi** {.unnumbered}

Menurut Pintrich & Groot (2003) motivasi umumnya berkaitan dengan energi dan arah perilaku manusia yang  dapat dipahami dalam konteks teori sosial kognitif dimana hipotesis tentang hubungan antara motivasi dan membaca dapat diturunkan. Teori tersebut berpendapat bahwa tindakan individu didorong oleh pemikiran, tujuan, keyakinan, dan nilai bukan konsekuensi perilaku yang diperkirakan (Schunk, 1991). Teori motivasi modern tidak hanya menganggap motivasi sebagai karakteristik individu, tetapi juga mengakui dampak penting dari konteks sosial dan hubungan interpersonal pada motivasi (Zhang dkk., 2020). Menurut Eccles & Wigfield (2002) motivasi adalah konstruksi yang mencakup keyakinan belajar, tujuan, nilai-nilai yang mempengaruhi pilihan aktivitas. Motivasi membaca adalah konstruk multidimensi, namun belum ada konsensus mengenai jumlah atau sifat dimensi yang terlibat dan ukuran membaca telah mencerminkan fragmentasi tersebut. Motivasi membaca dapat didefinisikan sebagai sejauh mana seorang siswa memiliki niat untuk membaca teks dalam situasi tertentu.Terdapat dua kelompok konstruksi yang mengacu pada bentuk motivasi membaca, yaitu motivasi membaca intrinsik atau ekstrinsik serta motivasi membaca yang berhubungan dengan prasyarat motivasi membaca, seperti membaca konsep diri (Schiefele dkk., 2012).

Motivasi membaca intrinsik dapat didefinisikan sebagai kemauan untuk membaca karena dengan aktivitas membaca tersebut akan memberikan manfaat untuk dirinya sendiri. Motivasi intrinsik dapat terjadi karena seseorang memiliki minat terhadap topik sebuah teks dan mereka termotivasi untuk membaca karena membaca memberikan pengalaman yang positif. Sedangkan motivasi ekstrinsik mengacu pada alasan diluar aktivitas membaca teks dan topik teks. Seseorang yang termotivasi secara ekstrinsik bercita-cita untuk mendapatkan hasil yang positif, misalnya siswa yang membaca teks di sekolah agar mendapat pujian dari guru dan teman-temannya diri (Schiefele dkk., 2012).

### **5. Iklim Sekolah** {.unnumbered}

Iklim sekolah merupakan salah satu hal yang sulit untuk didefinisikan, namun semua orang dapat merasakan bagaimana iklim sekolah mereka. Iklim sekolah digambarkan sebagai kualitas dan karakter kehidupan sekolah serta kualitas hubungan antara siswa, guru, dan staf sekolah (Berkowitz dkk., 2017). Sekolah dengan iklim yang positif dapat meningkatkan prestasi akademik dan kesejahteraan siswa (Hoge dkk., 1990). Menurut  Berkowitz dkk. (2017) iklim yang positif berhubungan kuat dengan status sosial ekonomi dan prestasi akademik.

Thapa dkk. (2013) menyebutkan empat indikator yang membentuk iklim sekolah, yaitu keamanan (termasuk perilaku intimidasi, pembolosan, disiplin), pembelajaran dan pengajaran (termasuk dukungan akademik, antusias belajar dan mengajar, aspek kurikulum pembelajaran), komunitas sekolah (seperti hubungan siswa dengan guru, keterlibatan orang tua, hubungan sekolah dengan masyarakat), dan lingkungan sekolah (seperti fasilitas sekolah, ukuran kelas, dan teknologi pendidikan). Sedangkan menurut Karaman (2022) iklim sekolah terbentuk dari tiga indikator yaitu iklim disiplin, persepsi kompetisi siswa di sekolah, dan persepsi kerjasama siswa di sekolah. Penjelasan dari indikator-indikator tersebut adalah sebagai berikut.

#### a. Iklim Disiplin {.unnumbered}

Salah satu hal yang membuat lingkungan kelas menjadi kondusif adalah iklim disiplin, yaitu jauh bahkan tidak ada kebisingan dan kekacauan di kelas, siswa mendengarkan  apa yang guru katakan, serta siswa dapat berkonsentrasi pada tugas akademik (Moos, 1980). Cheema & Kitsantas (2014) mendefinisikan iklim disiplin sebagai persepsi bahwa siswa berpegang pada konsistensi aturan kelas dan bagaimana guru mengatasi masalah di kelas. Sedangkan dalam  PISA, iklim sekolah diukur dengan sejauh mana siswa kehilangan kesempatan belajar karena perilaku yang mengganggu di kelas (OECD, 2019b).

Penelitian sebelumnya menunjukkan bahwa sekolah dengan sosial ekonomi yang tinggi biasanya memiliki iklim disiplin yang yang lebih baik dibandingkan dengan sekolah yang memiliki sosial ekonomi rendah (Ma & Willms, 2004). Ruang kelas dengan iklim disiplin yang baik akan membuat lingkungan kelas lebih sedikit mengalami gangguan sehingga siswa lebih berkonsentrasi saat belajar (Mostafa & Echazarra, 2018). Hasil PISA sebelumnya juga menunjukkan bahwa terdapat hubungan positif antara persepsi siswa terhadap iklim disiplin kelas dan prestasi akademik (OECD, 2016).

#### b. Persepsi Kompetisi dan Kerjasama Siswa di Sekolah {.unnumbered}

Penelitian menunjukkan bahwa siswa yang memiliki prestasi akademik, memiliki hubungan yang baik dengan teman sekelas dan memiliki ikatan yang kuat dengan sekolah dalam lingkungan akademik yang kooperatif daripada lingkungan yang kompetitif (Johnson dkk., (1981); Roseth dkk., (2008)). Namun menurut Madrid dkk. (2007) dan Johnson & Johnson (1974) lingkungan akademik yang kompetitif dapat meningkatkan prestasi akademik dan meningkatkan kecepatan dalam belajar. Menurut Kistruck dkk. (2014) jiwa kompetisi menyebabkan motivasi yang lebih besar dan menurut Morschheuser dkk. (2019) ketika kompetisi dan kerjasama disatukan, seperti dalam kompetisi antar tim, kinerja dan kesenangan peserta lebih tinggi dibandingkan pada lingkungan yang murni kerjasama atau kompetisi.

### **6. Kesejahteraan Siswa** {.unnumbered}

Kesejahteraan *(well-being)* didefinisikan sebagai kebutuhan material maupun non material dalam keadaan tertentu yang memungkinkan individu merasa puas akan kebutuhan-kebutuhan dasarnya, yang meliputi *having, loving,* dan *being* (Konu dkk., 2002)*.* Kesejahteraan subjektif mengacu pada bagaimana seseorang merasakan atau mengalami kesenangan dalam hidupnya (Diener dkk., 1999).Bücker dkk. (2018)menyatakan bahwa kesejahteraan anak memiliki efek positif pada kendali internal, harga diri, dan motivasi intrinsik mereka. Kesejahteraan juga memungkinkan anak-anak untuk membangun keterampilan dan sumber daya baru, yang akhirnya dapat mengarah pada peningkatan prestasi akademik.

Kesejahteraan siswa mengacu pada fungsi dan kemampuan psikologis, kognitif, material, fisik dan sosial yang dimiliki siswa sehingga mampu menjalani kehidupan yang memuaskan dan membahagiakan  (OECD, 2017). Lima domain kesejahteraan siswa tersebut menurut Borgonovi & Pal (2016) adalah sebagai berikut.

a\. Kesejahteraan kognitif, mengacu pada pengetahuan, keterampilan, dan fondasi yang dimiliki siswa untuk berpartisipasi secara aktif di masyarakat.

b\. Kesejahteraan psikologis, meliputi evaluasi dan pandangan siswa terhadap kehidupan mereka dengan sekolah, serta tujuan dan ambisi mereka untuk masa depan.

c\. Kesejahteraan material, mengacu pada sumber daya materi yang memungkinkan keluarga untuk menyediakan kebutuhan anak-anak mereka dan memungkinkan sekolah untuk mendukung pembelajaran dan perkembangan siswa.

d\. Kesejahteraan fisik, mengacu pada kesehatan siswa, keterlibatan siswa dalam latihan fisik dan kebiasaan makan.

e\. Kesejahteraan sosial, mengacu pada kualitas kehidupan sosial mereka, termasuk hubungan siswa dengan teman sebaya, guru dan bagaimana mereka memandang kehidupan sosial mereka di sekolah (Pollard & Lee, 2002).

Dalam PISA 2018 kesejahteraan siswa terdiri dari dimensi kognitif dan dimensi psikologi. Dimensi kognitif terdiri dari pola pikir berkembang (*growth mindset*)*,* sedangkan dimensi psikologi terdiri dari kepuasan hidup dan makna hidup siswa, perasaan siswa, efikasi diri dan takut gagal siswa (OECD, 2019c). Dalam penelitian ini menggunakan indikator kepuasan hidup siswa, perasaan siswa, efikasi diri dan pola pikir berkembang untuk menggambarkan tingkat kesejahteraan siswa di Indonesia. Penjelasan indikator-indikator tersebut dinyatakan sebagai berikut:

#### a. Kepuasan Hidup dan Makna Hidup Siswa (*student\'s life satisfaction and meaning in life*) {.unnumbered}

Kepuasan hidup dapat didefinisikan sebagai penilaian subjektif terhadap kualitas hidup seseorang (Diener dkk, 1999). Kepuasan hidup merupakan evaluasi yang dibuat seseorang mengenai kualitas hidup yang ia rasakan berdasarkan kriteria pilihannya (Watson & Clark, 1988).  Menurut Diener (1984) kriteria kepuasan hidup umumnya diukur dengan beberapa indikator seperti kesehatan, keuangan yang stabil, dan kondisi lingkungan. Penelitian Suldo & Huebner (2004) menunjukkan bahwa prestasi meningkatkan kepuasan hidup dan memotivasi siswa untuk belajar lebih keras, namun menurut Chang dkk. (2003) hubungan antara prestasi akademik dan kepuasan hidup masih kurang jelas. Hasil PISA 2015 menunjukkan bahwa siswa yang berprestasi rendah cenderung memiliki kepuasan hidup yang tinggi, namun beberapa negara dengan tingkat kepuasan hidup siswa yang tinggi juga menghasilkan prestasi akademik yang tinggi, seperti siswa di Finlandia, Belanda, dan Swiss (OECD, 2017).

#### b. Perasaan Positif Siswa (*student\'s feelings*) {.unnumbered}

Perasaan dapat didefinisikan sebagai sejauh mana seseorang mengalami emosi dan suasana hati pada waktu tertentu (Watson & Clark, 1988). Perasaan siswa adalah suatu hal yang penting karena berkaitan dengan akademik dan kesejahteraan siswa. Menurut teori Broaden and Build, perasaan positif seperti kebahagiaan, kebanggaan, kenikmatan dan kecintaan mendorong siswa untuk bereksplorasi, bercita-cita, bermain, berkreasi, dan meningkatkan keterampilannya (Fredrickson, 2001). Perasaan positif berhubungan positif dengan motivasi, efikasi diri (*self-efficacy*)*,* dan keterlibatan siswa di sekolah, serta secara tidak langsung perasaan  positif  berhubungan dengan prestasi akademik (King dkk., 2015).

#### c. Efikasi Diri (*Self efficacy)* dan rasa takut gagal (*fear of failure*) {.unnumbered}

Efikasi diriadalah sejauh mana seseorang percaya terhadap kemampuan mereka sendiri untuk terlibat dalam kegiatan dan melaksanakan tugas-tugas tertentu terutama ketika menghadapi keadaan yang merugikan (Bandura, 1978).  Efikasi diri dan rasa takut akan gagal (*fear of failure*) berjalan beriringan, siswa yang percaya bahwa mereka mampu dalam situasi tertentu akan merasa cenderung lebih takut saat berada di situasi yang lain. Bagaimana siswa menilai kemampuan mereka dan seberapa mereka takut gagal dapat membentuk motivasi, perasaan, dan perilaku mereka (Bandura, 1991). Siswa dengan efikasi diri cenderung menetapkan tujuan yang lebih menantang, berusaha lebih keras dan bertahan lama karena mereka yakin akan berhasil (Bandura, 1999). Sebaliknya siswa yang kurang percaya diri mungkin salah berasumsi bahwa ketika mereka terlalu banyak berusaha akan membuang-buang waktu dan berpikir kemungkinan untuk sukses menjadi kecil (Bandura dkk., 2001).

#### d. Pola Pikir Berkembang Siswa (*growth mindset*) {.unnumbered}

Pola pikir berkembang (*growth mindset*) merupakan keyakinan bahwa kemampuan dan kecerdasan seseorang dapat berkembang dalam suatu waktu. Hal tersebut berbeda dengan *mindset* tetap, yakni keyakinan bahwa seseorang dilahirkan dengan kemampuan dan kecerdasan yang hampir tidak bisa berubah karena pengalaman (Dweck, 2006). Menanamkan pola pikir berkembang dianggap sebagai salah satu strategi untuk membantu siswa dalam belajar. Namun tidak hanya itu, siswa yang memiliki pola pikir berkembang juga menggunakan strategi lain untuk meningkatkan belajar mereka, seperti belajar dari pengalaman sebelumnya, melakukan evaluasi terhadap pembelajaran yang telah mereka lakukan, dan mencoba strategi baru untuk belajar (Yeager & Dweck, 2012). Menurut beberapa penelitian, menanamkan pola pikir berkembang pada siswa dapat meningkatkan motivasi belajar dan menghasilkan kinerja akademik yang lebih baik (Blackwell dkk., (2007); Sriram, (2013);  Mccutchen dkk., (2015)). Hal tersebut dikarenakan, seorang siswa yang memiliki pola pikir berkembang akan menggunakan berbagai strategi belajar tanpa takut gagal.
