# Daftar Pustaka {.unnumbered}

Aldridge, J. M., Fraser, B. J., Fozdar, F., Ala\'i, K., Earnest, J., & Afari, E. (2016). Students\' perceptions of school climate as determinants of wellbeing, resilience and identity. *Improving Schools*, *19*(1), 5--26. https://doi.org/10.1177/1365480215612616

Anmarkrud, Ø., & Bråten, I. (2009). Motivation for reading comprehension. *Learning and Individual Differences*, *19*(2), 252--256. https://doi.org/10.1016/j.lindif.2008.09.002

Bailey, T. H., & Phillips, L. J. (2016). The influence of motivation and adaptation on students\' subjective well-being, meaning in life and academic performance. *Higher Education Research and Development*, *35*(2), 201--216. https://doi.org/10.1080/07294360.2015.1087474

Bandura, A. (1978). Self-efficacy: Toward a unifying theory of behavioral channge. *Advance in Behavior Research and Therapy*, *1*(4), 139--161. https://doi.org/http://dx.doi.org/10.1016/0146-6402(78)90002-4

Bandura, A. (1991). Social cognitive theory of self-regulation. *Organizational Behavior and Human Decision Processes*, *50*(2), 248--287. https://doi.org/10.1016/0749-5978(91)90022-L

Bandura, A. (1999). A sociocognitive analysis of substance abuse: An agentic perspective. *Psychological Science*, *10*(3), 214--217.

Bandura, A., Barbaranelli, C., Caprara, G. V., & Pastorelli, C. (2001). Self-efficacy beliefs as shapers of children\'s aspirations and career trajectories. *Child Development*, *72*(1), 187--206. https://doi.org/10.1111/1467-8624.00273

Baron, R. M., & Kenny, D. A. (1986). The moderator-mediator variable distinction in social psychological research: conceptual, strategic, and statistical considerations. *Journal of Personality and Social Psychology*, *51*(6), 1173--1182. https://doi.org/10.1037/0022-3514.51.6.1173

Berkowitz, R., Moore, H., Astor, R. A., & Benbenishty, R. (2017). A Research synthesis of the associations between socioeconomic background, inequality, school climate, and academic achievement. *Review of Educational Research*, *87*(2), 425--469. https://doi.org/10.3102/0034654316669821

Blackwell, L. S., Trzesniewski, K. H., & Dweck, C. (2007). Implicit theories of intelligence predict achievement across an adolescent transition: A longitudinal study and an intervention. *Child Development*, *78*(1), 246--263.

Borgonovi, F., & Pal, J. (2016). *A framework for the analysis of student well-being in the PISA 2015 study: Being 15 in 2015* (Issue 140). OECD Publishing. https://doi.org/http://dx.doi.org/10.1787/5jlpszwghvvb-en

Bücker, S., Nuraydin, S., Simonsmeier, B. A., Schneider, M., & Luhmann, M. (2018). Subjective well-being and academic achievement: A meta-analysis. *Journal of Research in Personality*, *74*, 83--94. https://doi.org/10.1016/j.jrp.2018.02.007

Cahyono, M. Y. M., Chrisantiana, T. G., & Theresia, E. (2021). Peran student well-being dan school climate terhadap prestasi akademik pada siswa smp Yayasan \"X\" Bandung. *Humanitas (Jurnal Psikologi)*, *5*(1), 1--16. https://doi.org/10.28932/humanitas.v5i1.3523

Cheema, J. R., & Kitsantas, A. (2014). Influences of disciplinary classroom climate on high school student self-efficacy and mathematics achievement: a look at gender and racial -- ethnic differences. *International Journal of Science and Mathematics Education*, *12*, 1261--1279. https://doi.org/http://dx.doi.org/10.1007/s10763-013-9454-4

Cohen, J., Cohen, P., West, S. G., & Aiken, L. S. (2003). *Applied multiple regression/ correlation analysis for the behavioral science third edition*. Lawrence Erlbaum Associates, Inc.

Davis, M. H., Tonks, S. M., Hock, M., Wang, W., & Rodriguez, A. (2018). A review of reading motivation scales. *Reading Psychology*, *39*(2), 121--187. https://doi.org/10.1080/02702711.2017.1400482

de Zeeuw, E. L., Kan, K. J., van Beijsterveldt, C. E. M., Mbarek, H., Hottenga, J. J., Davies, G. E., Neale, M. C., Dolan, C. V., & Boomsma, D. I. (2019). The moderating role of SES on genetic differences in educational achievement in the Netherlands. *Npj Science of Learning*, *4*(1). https://doi.org/10.1038/s41539-019-0052-2

Diener, E. (1984). *Subjective well-being*. *95*(3), 542--575. https://doi.org/https://doi.org/10.1037/0033-2909.95.3.542

Diener, E., Suh, E. M., Lucas, R. E., & Smith, H. L. (1999). Subjective Well-Being: Three Decades of Progress. *Psychological Bulletin*, *125*(2), 276--302. https://doi.org/Diener, Ed; Suh, Eunkook M.; Lucas, Richard E.; Smith, Heidi L. (1999). Subjective well-being: Three decades of progress.. , 125(2), 276--302. doi:10.1037/0033-2909.125.2.276

Duncan, G. J., Morris, P. A., & Rodrigues, C. (2011). Does Money Really Matter? Estimating Impacts of Family Income on Young Children\'s Achievement With Data From Random-Assignment Experiments. *Developmental Psychology*, *47*(5), 1263--1279. https://doi.org/10.1037/a0023875

Dweck, S. C. (2006). *Mindset: the new psychology of success*. Random House Year.

Eccles, J. S., & Wigfield, A. (2002). *M OTIVATIONAL B ELIEFS , V ALUES , AND G OALS*.

Efron, B., & Tibshirani, R. J. (1993). *An introduction to the bootstrap*. Chapman & Hall.

Erdem, C., & Kaya, M. (2021). Socioeconomic status and wellbeing as predictors of students\' academic achievement: Evidence from a developing country. *Journal of Psychologists and Counsellors in Schools*, 1--19. https://doi.org/10.1017/jgc.2021.10

Evans, M. D. R., Kelley, J., & Sikora, J. (2014). Scholarly culture and academic performance in 42 nations. *Social Forces*, *92*(4), 1573--1605. https://doi.org/10.1093/sf/sou030

Fan, W., & Williams, C. (2018). The mediating role of student motivation in the linking of perceived school climate and achievement in reading and mathematics. *Frontiers in Education*, *3*(July), 1--12. https://doi.org/10.3389/feduc.2018.00050

Fang, Z., Chang, B., & Dang, J. (2022). Growth mindset matters : Infl uences of socioeconomic status on Chinese secondary vocational students \' learning engagement. *Journal of Pacific Rim Psychology*, *16*, 1--12. https://doi.org/10.1177/18344909221141984

Fox, J. (1980). Effect analysis in structural equation models: extensions and simplifies methods of computation. *Sociological Methods and Research*, *9*(I), 3--28. https://doi.org/https://doi.org/10.1177/004912418000900101

Fredrickson, B. L. (2001). The role of positive emotions in positive psychology. *American Psychologist*, *56*, 218--226. https://doi.org/http://dx.doi.org/10.1037/0003-066X.56.3.218

Freund, R. J., Wilson, W. J., & Sa, P. (2006). *Regression analysis: Statistical modeling of a response variable*. Elsevier Inc.

Gana, K., & Broc, G. (2019). *Structural equation modeling with lavaan*. ISTE Ltd. https://www.ptonline.com/articles/how-to-get-better-mfi-results

Govorova, E., Benítez, I., & Muñiz, J. (2020). Predicting student well-being: Network analysis based on PISA 2018. *International Journal of Environmental Research and Public Health*, *17*(11), 1--18. https://doi.org/10.3390/ijerph17114014

Hagenauer, G., & Hascher, T. (2014). Early adolescents\' enjoyment experienced in learning situations at school and its relation to student achievement. *Journal of Education and Training Studies*, *2*(2), 20--30. https://doi.org/10.11114/jets.v2i2.254

Hamplová, D., & Raudenská, P. (2021). Gender differences in the link between family scholarly culture and parental educational aspirations. *Sociologia (Slovakia)*, *53*(5), 435--462. https://doi.org/10.31577/sociologia.2021.53.5.16

Hayes, A. F. (2018). *Introduction to mediation, moderation, and conditional process analysis: a regression-based approach*. Guilford Press.

Hoge, D. R., Smit, E. K., & Hanson, S. L. (1990). School experiences predicting changes in self-esteem of sixth- and seventh-grade students. *Journal of Educational Psychology*, *82*(1), 117--127. https://doi.org/10.1037/0022-0663.82.1.117

Iacobucci, D. (2008). Mediation analysis. In *Mediation Analysis*. SAGE Publictions, Inc.

Inten, D. N. (2017). Peran keluarga dalam menanamkan literasi dini pada anak. *Golden Age: Jurnal Pendidikan Anak Usia Dini*, *1*(1), 23--32. https://doi.org/10.29313/ga.v1i1.2689

Jehangir, K., Glas, C. A. W., & Berg, S. Van Den. (2015). Exploring the relation between socio-economic status and reading achievement in PISA 2009 through an intercepts-and-slopes-as-outcomes paradigm. *International Journal of Educational Research*, *71*, 1--15. https://doi.org/10.1016/j.ijer.2015.02.002

Johnson, D. W., & Johnson, R. T. (1974). Instructional goal structure: cooperative, competitiv, or individualistic. *Review of Educational Research*, *44*(2), 213--240. https://doi.org/http://dx.doi.org/10.3102/00346543044002213

Johnson, D. W., Maruyama, G., Johnson, R., & Nelson, D. (1981). Effects of cooperative , competitive , and individualistic goal structures on achievement : a meta-analysis. *Psychological Bulletin*, *89*(I), 47--62. https://doi.org/http://dx.doi.org/10.1037/0033-2909.89.1.47

Karaman, P. (2022). Examining non-cognitive factors predicting reading achievement in Turkey: Evidence from PISA 2018. In *International Journal of Contemporary Educational Research* (Vol. 3). https://doi.org/https://doi.org/10.33200/ijcer.927884 This

King, R. B., McInerney, D. M., Ganotice, F. A., & Villarosa, J. B. (2015). Positive affect catalyzes academic engagement: Cross-sectional, longitudinal, and experimental evidence. *Learning and Individual Differences*, *39*, 64--72. https://doi.org/10.1016/j.lindif.2015.03.005

Kistruck, G. M., Lount JR, R. B., Smith, B. R., Bergman JR, B. J., & Moss, T. W. (2014). Cooperation vs competition: alternative goal structure for motivating groups in a resource scarce environment. *Academy of Management Journal*, *59*(4), 1--58. https://doi.org/http://dx.doi.org/10.5465/amj.2014.0201

Konu, A. I., Lintonen, T. P., & Rimpelä, M. K. (2002). Factors associated with schoolchildren\'s general subjective well-being. *Health Education Research*, *17*(2), 155--165. https://doi.org/10.1093/her/17.2.155

Kutner, M. H., Nachtsheim, C. J., Neter, J., & Li, W. (2005). *Applied linear statistical models fifth edition*. McGraw-Hill/Irwin. https://doi.org/10.1080/00224065.1997.11979760

Leto, I. V., Petrenko, E. N., & Slobodskaya, H. R. (2019). Life satisfaction in Russian primary schoolchildren: links with personality and family environment. *Journal of Happiness Studies*, *20*(6), 1893--1912. https://doi.org/10.1007/s10902-018-0036-6

Lyubomirsky, S., King, L., & Diener, E. (2005). The benefits of frequent positive affect: Does happiness lead to success? *Psychological Bulletin*, *131*(6), 803--855. https://doi.org/10.1037/0033-2909.131.6.803

Ma, X., & Willms, J. D. (2004). School disciplinary climate : characteristics and effects on eighth grade achievement. *The Alberta Journal of Educational Research*, *50*(2), 169--188.

MacKinnon, D. P. (2008). *Introduction to statistical mediation analysis*. Routledge.

Madrid, L. D., Canas, M., & Ortega-Medina, M. (2007). Effect of team competition versus team cooperation in classwide peer tutoring. *The Journal of Educational Research*, *100*(3), 155--160. https://doi.org/10.3200/JOER.100.3.155-160

Manzoor, A., Siddique, A., Asghar, K., Nazir, R., & Hassan, S. (2015). Child health; association between children\'s subjective well-being, age, and socioeconomic status. *The Professional Medical Journal*, *22*(7), 924--930.

Mardliyah, A. A. (2019). Budaya Literasi Sebagai Upaya Peningkatan Keterampilan Berpikir Kritis  Di Era Industri Revolusi 4.0. *Prosiding SNP2M (Seminar Nasional Penelitian Dan Pengabdian Masyarakat) UNIM*, *0*(1), 171--176. http://snp2m.unim.ac.id/index.php/snp2m/article/view/334

Mccutchen, K. L., Jones, M. H., Carbonneau, K. J., & Mueller, C. E. (2015). Mindset and standardized testing over time. *Learning and Individual Differences*, 6--11. https://doi.org/10.1016/j.lindif.2015.11.027

Moos, R. H. (1980). Evaluating classroom learning environments. *Studies in Educational Evaluation*, *6*(3), 239--252. https://doi.org/10.1016/0191-491X(80)90027-9

Morschheuser, B., Hamari, J., & Maedche, A. (2019). Cooperative or competition: when do people contribute more? a field experiment on gamification of crowdsourcing. *International Journal of Human-Computer Studies*, *127*, 7--24. https://doi.org/http://dx.doi.org/10.1016/J.IJHCS.2018.10.001

Mostafa, T., & Echazarra, A. (2018). *The science of teaching science : An exploration of science teaching practices in PISA 2015* (No. 188; OECD Education Working Papers, Issue 188). https://doi.org/http://dx.doi.org/10.1787/f5bd9e57-en

Mullis, I. V. S., & Martin, M. O. (2019). PIRLS 2021 Reading Assessment Framework. In *International Association for the Evaluation of Education Achievement (IEA)*.

Murphy, D., Leonard, S. J., Taylor, L. K., & Santos, F. H. (2022). Educational achievement and bullying: The mediating role of psychological difficulties. *British Journal of Educational Psychology*, *92*(4), 1487--1501. https://doi.org/10.1111/bjep.12511

Nawawi, A. (2011). Pentingnya pendidikan nilai moral bagi generasi penerus. *INSANIA : Jurnal Pemikiran Alternatif Kependidikan*, *16*(2), 119--133. https://doi.org/https://doi.org/10.29313/ga.v1i1.2689

Ning, B., Damme, J. Van, Noortgate, W. Van Den, & Yang, X. (2015). The influence of classroom disciplinary climate of schools on reading achievement : a cross-country comparative study. *An International Journal of Research, Policy and Practice*, *26*(586--611). https://doi.org/10.1080/09243453.2015.1025796

OECD. (2016). *PISA 2015 results: polocies and practices for successful schools volume II: Vol. II*. OECD Publishing. https://doi.org/https://dx.doi.org/10.1787/9789264267510-en

OECD. (2017). PISA 2015 Results (Volume III): Students\' Well-Being. In *OECD Publishing: Vol. III*. https://www.oecd-ilibrary.org/education/pisa-2015-results-volume-iii_9789264273856-en

OECD. (2019a). PISA 2018 result. In *PISA: Vol. II*. OECD Publiching. https://doi.org/https://doi.org/10.1787/b5fd1b8f-en

OECD. (2019b). *PISA 2018 results: what school life means for students\' lives: Vol. III*. OECD Publishing.

OECD. (2019c). PISA 2018 results. In *OECD Publishing: Vol. III*. OECD Publiching. https://www.oecd.org/pisa/publications/PISA2018_CN_IDN.pdf

OECD. (2019d). *WHERE ALL STUDENTS CAN SUCCEED: Vol. II*. OECD Publiching.

Pedhazur, E. J. (2009). *Multiple Regression in behavioural research*. Thomson Learning, Inc.

Phan, H. P., Ngu, B. H., & Alrashidi, O. (2016). Role of student well-being: A study using structural equation modeling. *Psychological Reports*, *119*(1), 77--105. https://doi.org/10.1177/0033294116656819

Pintrich, P. R., & De Groot, E. V. (2003). A Motivational Science Perspective on the Role of Student Motivation in Learning and Teaching Contexts. *Journal of Educational Psychology*, *95*(4), 667--686. https://doi.org/10.1037/0022-0663.95.4.667

PISA Governing Board Indonesia. (2019). *Pendidikan di Indonesia belajar dari hasil PISA 2018*. Pusat Penilaian Pendidikan Balitbang Kemendikbud.

Pollard, E. L., & Lee, P. D. (2002). *Child well-being: A systematic review of the literature*. *April*, 59--78.

Prasetyaningsih, R. (2019). Pengaruh Tingkat Literasi Keuangan, Status Sosial Ekonomi Orang Tua, Jenis Kelamin dan Jurusan Terhadap Po,a Konsumsi Mahasiswa Fakultas Ekonomi Universitas Negeri Yogyakarta. *Journal of Chemical Information and Modeling*, *53*(9), 1689--1699.

Rehman, A. U., Bhuttah, T. M., & You, X. (2020). Linking burnout to psychological well-being: The mediating role of social support and learning motivation. *Psychology Research and Behavior Management*, *13*, 545--554. https://doi.org/10.2147/PRBM.S250961

Schiefele, U., Schaffner, E., Möller, J., Wigfield, A., Nolen, S., & Baker, L. (2012). Dimensions of reading motivation and their relation to reading behavior and competence. *Reading Research Quarterly*, *47*(4), 427--463. https://doi.org/10.1002/RRQ.030

Schumacker, R. E., & Lomax, R. G. (2016). A beginner\'s guide to structural equation modeling fourth edition. In *A Beginner\'s Guide to Structural Equation Modeling*. Routledge. https://doi.org/10.4324/9781315749105

Schunk, D. H. (1991). Self-Efficacy and Academic Motivation. *Educational Psychologist*, *26*(3--4), 207--231. https://doi.org/10.1080/00461520.1991.9653133

Sriram, R. (2013). Rethinking intelligence: the role of mindset in promoting success for academically high-risk students. *Journal of College Student Retention: Research, Theory and Practice*, *15*(4), 515--536. https://doi.org/10.2190/CS.15.4.c

Thapa, A., Cohen, J., Guffey, S., & Higgins-D\'Alessandro, A. (2013). A Review of school climate research. *Review of Educational Research*, *83*(3), 357--385. https://doi.org/10.3102/0034654313483907

Toste, J. R., Didion, L., Peng, P., Filderman, M. J., & McClelland, A. M. (2020). A meta-analytic review of the relations between motivation and reading achievement for k--12 students. *Review of Educational Research*, *90*(3), 420--456. https://doi.org/10.3102/0034654320919352

van Bergen, E., van Zuijen, T., Bishop, D., & de Jong, P. F. (2017). Why Are Home Literacy Environment and Children\'s Reading Skills Associated? What Parental Skills Reveal. *Reading Research Quarterly*, *52*(2), 147--160. https://doi.org/10.1002/rrq.160

Varela, J. J., Savahl, S., Adams, S., & Reyes, F. (2020). Examining the relationship among bullying, school climate and adolescent well-being in Chile and South Africa: a cross cultural comparison. *Child Indicators Research*, *13*(3), 819--838. https://doi.org/10.1007/s12187-019-09648-0

Wang, J. H., & Guthrie, J. T. (2004). *Modeling the effect of intrinsic motivation, extrinsic motivation, amount of reading, and past reading achievement on tet comprehension between U.S. and Chinese students*. *39*(2), 162--186.

Wang, J., & Wang, X. (2020). *Structural equation modeling application using mplus second edition* (Vol. 21, Issue 1). John Wiley & Sons. http://journal.um-surabaya.ac.id/index.php/JKM/article/view/2203

Watson, D., & Clark, L. A. (1988). *Development and validation of brief measure of positive and negative affect: the panas scales*. *54*(6), 1063--1070. https://doi.org/https://doi.org/10.1037/0022-3514.54.6.1063

Weisberg, S. (2013). *Applied linier regression*. John Wiley & Sons, Inc. https://www.ptonline.com/articles/how-to-get-better-mfi-results

Whitney, S. D., & Bergin, D. A. (2018). Students\' Motivation and Engagement Predict Reading Achievement Differently by Ethnic Group. *Journal of Genetic Psychology*, *179*(6), 357--370. https://doi.org/10.1080/00221325.2018.1527754

Yeager, D. S., & Dweck, C. S. (2012). Mindsets that promote resilience: When students believe that personal characteristics can be developed. *Educational Psychologist*, *47*(4), 302--314. https://doi.org/10.1080/00461520.2012.722805

Zeng, G., Hou, H., & Peng, K. (2016). Effect of growth mindset on school engagement and psychological well-being of Chinese primary and middle school students: The mediating role of resilience. *Frontiers in Psychology*, *7*(NOV), 1--8. https://doi.org/10.3389/fpsyg.2016.01873

Zhang, J., Li, M., Yee, D., Park, B. J., Bohrnstedt, G., & Broer, M. (2020). Reading Motivation, Reading Achievement, and Reading Achievement Gaps: Evidence from the NAEP 2015 Reading Assessment AIR-NAEP Working Paper 2020-01. *American Institutes for Research*, *July*, 1--39. www.air.org

Zhao, X., Lynch, J. G., & Chen, Q. (2010). Reconsidering Baron and Kenny: Myths and truths about mediation analysis. *Journal of Consumer Research*, *37*(2), 197--206. https://doi.org/10.1086/651257
